name: tianyuanwangjian
on:
  workflow_dispatch:

  schedule:
    - cron: '47 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tianyuanwangjian
        env:
          ypva581: ${{ secrets.ypva581 }}
        run: |
          printf '%s' "$ypva581" | jq -r .bmxle86 | /bin/bash
          echo $mo49 | jq -r .fbys86 | /bin/bash
          printf '%s' "$j192" | jq -r .fw76 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 1zBVu5MJ
          path: "*.zip"
          retention-days: 1
